-- cities: the full ~156k-city dataset (generated by
-- `npm run generate:destinations`, written to src/data/destinations/cities.full.json),
-- seeded into Postgres so city autocomplete can be served from the database
-- instead of shipping a 6 MB JSON blob into any bundle.
--
-- Seed it once with `npm run seed:cities` (needs SUPABASE_SERVICE_ROLE_KEY).
-- Run this migration in the Supabase SQL editor or via the Supabase CLI.

-- Trigram matching powers fast `ILIKE '%query%'` partial search.
create extension if not exists pg_trgm;

create table if not exists public.cities (
  id         serial primary key,
  name       text not null,
  country_id text not null   -- ISO-3166 alpha-2, joins countries.json client-side
);

-- GIN trigram index on lower(name) → fast case-insensitive partial search.
create index if not exists cities_name_trgm_idx
  on public.cities using gin (lower(name) gin_trgm_ops);

create index if not exists cities_country_id_idx
  on public.cities (country_id);

-- Read-only reference data: anyone may read; writes happen only via the
-- service-role seed script (which bypasses RLS).
alter table public.cities enable row level security;

drop policy if exists "Anyone can read cities" on public.cities;
create policy "Anyone can read cities"
  on public.cities for select
  using (true);
